# MIT License

# Copyright (c) 2020 Hongrui Zheng

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3'
services:
  sim:
    build: ./f1tenth_gym_ros
    volumes:
      - ./f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
      - /dev/input:/dev/input
    environment:
      - DISPLAY=selenoid_vnc:99.0
    networks:
      - x11
    ports:
      # rosbridge
      - "9090:9090"
    stdin_open: true
    tty: true
    devices:
      - /dev/input/js0:/dev/input/js0
      - /dev/input/js1:/dev/input/js1
    privileged: true
    # depends_on:
    #   - selenoid_vnc # wait for vnc to start

# very heavy, since it has chrome
# but it's the only vnc container i can find that works
  selenoid_vnc:
    image: selenoid/vnc:chrome_91.0
    container_name: selenoid_vnc
    ports:
      - "4444:4444"
      - "5900:5900"
    environment:
      - ENABLE_VNC=true
    cap_add:
      - SYS_ADMIN
    restart: "no"
    networks:
      - x11

  driver:
    build: ./f1tenth_drive
    volumes:
      - ./f1tenth_drive/src:/f1tenth_drive/src
    environment:
      - DISPLAY=selenoid_vnc:99.0
    networks:
      - x11
    stdin_open: true
    tty: true


networks:
  x11:
