# MIT License

# Copyright (c) 2020 Hongrui Zheng

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3'
services:
  sim:
    build: ./f1tenth_gym_ros
    volumes:
      - ./f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
      - /dev/input:/dev/input
      # Bind the X11 socket from the host
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pipewire-0:/tmp/pipewire-0
    environment:
      # Tell apps inside the container where to find the X11 display
      - XDG_RUNTIME_DIR=/tmp
      - DISPLAY=${DISPLAY}
    devices:
      # Mount Intel GPU and sound devices
      # - /dev/dri/card1:/dev/dri/card1
      # - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/snd
      - /dev/input/js0:/dev/input/js0
      - /dev/input/js1:/dev/input/js1
    stdin_open: true
    tty: true
    privileged: true
    # group_add:
    #     - 985  # video


  driver:
    build: ./f1tenth_drive
    volumes:
      - ./f1tenth_drive/src:/f1tenth_drive/src
      # Bind the X11 socket from the host
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pipewire-0:/tmp/pipewire-0
    environment:
      # Tell apps inside the container where to find the X11 display
      - XDG_RUNTIME_DIR=/tmp
      - DISPLAY=${DISPLAY}
      # Force Intel GPU usage
      - LIBGL_ALWAYS_INDIRECT=0
      - DRI_PRIME=0
      - MESA_LOADER_DRIVER_OVERRIDE=iris
    devices:
      # Mount Intel GPU and sound devices
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/snd
    stdin_open: true
    tty: true
